CREATE TABLE listings (
	title VARCHAR(60) NOT NULL DEFAULT '',
	description TEXT,
	category_code SMALLINT(4) UNSIGNED NOT NULL DEFAULT 0,
	member_id VARCHAR(15) NOT NULL DEFAULT '',
	rate VARCHAR(30) DEFAULT NULL,
	status CHAR(1) NOT NULL DEFAULT '',
	posting_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	expire_date DATE DEFAULT NULL,
	reactivate_date DATE DEFAULT NULL,
	type CHAR(1) NOT NULL DEFAULT '',
	PRIMARY KEY (title, category_code, member_id,type)
) ENGINE MyISAM DEFAULT CHARACTER SET utf8;
