CREATE TABLE categories (
	category_id SMALLINT(4) UNSIGNED NOT NULL AUTO_INCREMENT,
	parent_id SMALLINT(4) UNSIGNED DEFAULT NULL,
	description VARCHAR(40) NOT NULL DEFAULT '',
	PRIMARY KEY (category_id)
) ENGINE MyISAM DEFAULT CHARACTER SET utf8;
