CREATE TABLE feedback_rebuttal (
	rebuttal_id MEDIUMINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
	rebuttal_date TIMESTAMP NOT NULL,
	feedback_id MEDIUMINT(8) UNSIGNED DEFAULT NULL,
	member_id VARCHAR(15) NOT NULL DEFAULT '',
	comment VARCHAR(255) DEFAULT NULL,
	PRIMARY KEY (rebuttal_id)
) ENGINE InnoDB DEFAULT CHARACTER SET utf8;
