CREATE TABLE news (
	news_id MEDIUMINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL DEFAULT '',
	description TEXT NOT NULL,
	sequence DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
	expire_date DATE DEFAULT NULL,
	PRIMARY KEY (news_id)
) ENGINE InnoDB DEFAULT CHARACTER SET utf8;
