CREATE TABLE uploads (
	upload_id MEDIUMINT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
	upload_date TIMESTAMP NOT NULL,
	title VARCHAR(100) NOT NULL DEFAULT '',
	type CHAR(1) NOT NULL DEFAULT '',
	filename VARCHAR(100) DEFAULT NULL,
	note VARCHAR(100) DEFAULT NULL,
	PRIMARY KEY (upload_id)
) ENGINE InnoDB DEFAULT CHARACTER SET utf8;
