CREATE TABLE income_ties (
	id INT(11) NOT NULL AUTO_INCREMENT,
	member_id VARCHAR(15) DEFAULT NULL,
	tie_id VARCHAR(15) DEFAULT NULL,
	percent INT(3) DEFAULT NULL,
	PRIMARY KEY  (id)
) ENGINE MyISAM AUTO_INCREMENT 12 DEFAULT CHARACTER SET utf8;
