CREATE TABLE cdm_pages (
	id int(11) NOT NULL AUTO_INCREMENT,
	date INT(30) DEFAULT NULL,
	title VARCHAR(255) DEFAULT NULL,
	body TEXT,
	active INT(1) DEFAULT 1,
	permission INT(2),
	PRIMARY KEY (id)
) ENGINE MyISAM AUTO_INCREMENT 6 DEFAULT CHARACTER SET utf8;
