<h2><?= _("(heading)Profile") ?></h2>
<ul>
	<li><a href="password_change.php"><?= _("(list_item)Change password") ?></a></li>
	<li><a href="member_edit.php?mode=self"><?= _("(list_item)Edit profile") ?></a></li>
	<li><a href="member_summary.php?member_id=<?= $memberId ?>"><?= _("(list_item)See my profile like others see it") ?></a></li>
	<li><a href="login_logout.php"><?= _("(list_item)Log out") ?></a></li>
</ul>
