<div style="background: white url(images/2mayo.jpeg) top left no-repeat; min-height: 550px">

<div style="margin: 0 1em 1em 400px; padding: .5em 1em; background: rgba(255, 255, 255, .8); text-align: right">
	<h1>a2Manos</h1>
	<p>El Banco de Tiempo de Malasaña-Dos de Mayo</p>
</div>

<div style="width: 300px; margin: 100px 1em 1em 0; padding: .5em 1em; background: rgba(255, 255, 255, .8)">
<p style="font-weight: bold">¿Por qué un BdT en el barrio?</p>
<ul>
	<li>Conoce mejor a tus vecin@s</li>
	<li>Utiliza tus habilidades para ayudar a l@s demás</li>
	<li>Reflexiona sobre el verdadero valor de las cosas y del tiempo</li>
	<li>Crea tejido social</li>
	<li>Sobre todo, aprende y diviértete</li>
</ul>

<?php if (!$isLoggedOn): ?>
	<p><a href="member_login.php">Pulse aqui para entrar</a></p>
<?php endif ?>
</div>

</div>