<div style="text-align: center">
	<h1>a2Manos</h1>
	<p>El Banco de Tiempo de Malasaña-Dos de Mayo</p>
</div>

<p style="font-weight: bold">¿Por qué un BdT en el barrio?</p>
<ul>
	<li>Conoce mejor a tus vecin@s</li>
	<li>Utiliza tus habilidades para ayudar a l@s demás</li>
	<li>Reflexiona sobre el verdadero valor de las cosas y del tiempo</li>
	<li>Crea tejido social</li>
	<li>Sobre todo, aprende y diviértete</li>
</ul>

<?php if (!$isLoggedOn): ?>
	<p><a href="member_login.php">Pulse aqui para entrar</a></p>
<?php endif ?>
