<h2>Intercambios</h2>

<ul>
	<li><a href="trades_pending.php">Transacciones pendientes &ndash; <?= $numIn ?></a></li>
	<li><a href="trade.php?mode=self">Insertar un intercambio</a></li>
	<li><a href="trade_history.php?mode=self">Ver mi saldo y historial de intercambios</a></li>
	<li><a href="trades_to_view.php">Ver historial de intercambios para otro soci@</a></li>
	<!--
		<li><a href="feedback_all.php?mode=self">View My Feedback</a></li>
		<li><a href="feedback_to_view.php">View Another Member's Feedback</a></li>
		<li><a href="feedback_choose.php?mode=self">Leave Feedback for a Recent Exchange</a></li>
	-->
	<li><a href="timeframe_choose.php?action=trade_history_all">Ver todos los intercambios en un rango de tiempo</a></li>
</ul>