<h2>Offered Listings</h2>
<ul>
	<li><a href="listing_create.php?type=Offer">Create New Offer Listing</a></li>
	<li><a href="listing_to_edit.php?type=Offer">Edit Offered Listings</a></li>
	<li><a href="listing_delete.php?type=Offer">Delete Offered Listings</a></li>
</ul>

<h2>Wanted Listings</h2>
<ul>
	<li><a href="listing_create.php?type=Want">Create New Want Listing</a></li>
	<li><a href="listing_to_edit.php?type=Want">Edit Wanted Listings</a></li>
	<li><a href="listing_delete.php?type=Want">Delete Wanted Listings</a></li>
</ul>