<h2>Mis servicios</h2>
<ul>
	<li><a href="listing_create.php?type=Offer&mode=self">Crear un nuevo servicio</a></li>
	<li><a href="listing_to_edit.php?type=Offer&mode=self">Editar servicios ofrecidos</a></li>
	<li><a href="listing_delete.php?type=Offer&mode=self">Borrar servicios ofrecidos</a></li>
</ul>

<h2>Servicios solicitados</h2>
<ul>
	<li><a href="listing_create.php?type=Want&mode=self">Crear un nuevo servicio solicitado</a></li>
	<li><a href="listing_to_edit.php?type=Want&mode=self">Editar servicios solicitados</a></li>
	<li><a href="listing_delete.php?type=Want&mode=self">Borrar servicios solicitados</a></li>
</ul>

<h2>Otros</h2>
<ul>
	<li><a href="holiday.php?mode=self">Voy de vacaciones</a></li>
</ul>
