CREATE TABLE cron (
	id				INT PRIMARY KEY,
	env				VARCHAR(80) NOT NULL,
	policy			VARCHAR(80) NOT NULL,
	policy_settings	TEXT NOT NULL,
	is_enabled		INT(1) UNSIGNED NOT NULL DEFAULT 1,
	is_running		INT(1) UNSIGNED NOT NULL DEFAULT 0,
	last_run		DATETIME DEFAULT NULL
) ENGINE InnoDB DEFAULT CHARSET utf8;
